### ISSUE TITLE
Thanks for this package

### ISSUE THREAD

**Issue by sferoze** [reywood/node-authorize-net-arb#1]
Hi,

Thanks so much for this package! I am making a cloud app for a customer and they want me to use authorize.net. I checked their website and they had no support for Node.js! I am using Meteor and Meteor can use server side npm modules. So I am really glad I found this package. 

I am use to stripe and they have a really simple API. How do you feel this compares? The package seems pretty straight forward. Any surprises in store for me?

**Comment by reywood** [comment]
I've been using this package is a production app with no problems for a while now. Haven't used Stripe, so I can't comment much on how it compares. Follow the advice in the README, and you should be fine.
